### PR TITLE
Environmentvars

### PR DESCRIPTION
**Pull request by williammai49**
this is the updated one, please ignore the old environmentvariable branch. this one also encapsulates the maps api key along with the places

### CODE REVIEW

**Comment by cyruskarsan** [comment]
@williammai49 Running the index.html in the root directory does not load for me. Is there some config I must do locally?

**Comment by cyruskarsan** [comment]
Screenshot from 2020-10-26 09-09-09

**Comment by cyruskarsan** [comment]
Can you also please delete the branch that is outdated?

**Comment by williammai49** [comment]
going up load another one sorry

**Pull request closed without merging**
